pipeline {
    agent  {
            label 'java11-build'
            /*image 'maven:3-alpine' */
            args '-v /root/.m2:/root/.m2'
        }
    stages {
        stage('Build') {
            steps {
                /*
                sh 'mvn -B -DskipTests clean package'
                */
                sh 'java  -version'
            }
        }
        /*
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        */
    }
}
